"""Add outage lifecycle fields

Revision ID: 33a97e1ac5b3
Revises: 4460b6562ead
Create Date: 2026-05-14 18:25:14.733221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a97e1ac5b3'
down_revision: Union[str, Sequence[str], None] = '4460b6562ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outages', sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outages', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    
    # Data migration for existing rows
    op.execute("UPDATE outages SET first_seen_at = COALESCE(start_time, created_at), last_seen_at = COALESCE(updated_at, created_at)")
    op.add_column('outages', sa.Column('missing_count', sa.Integer(), nullable=True))
    op.add_column('outages', sa.Column('is_stale', sa.Boolean(), nullable=True))
    op.add_column('outages', sa.Column('stale_reason', sa.String(), nullable=True))
    op.add_column('outages', sa.Column('resolution_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outages', 'resolution_type')
    op.drop_column('outages', 'stale_reason')
    op.drop_column('outages', 'is_stale')
    op.drop_column('outages', 'missing_count')
    op.drop_column('outages', 'last_seen_at')
    op.drop_column('outages', 'first_seen_at')
    # ### end Alembic commands ###
